# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user',
            name='t_username',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='t_user',
            name='t_userpsw',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
