# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_accountinvoice_accountinvoiceline_paymentmode_respartner_resusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('write_uid', models.IntegerField(blank=True, null=True)),
                ('rounding', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('symbol', models.CharField(blank=True, max_length=4, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('base', models.NullBooleanField()),
                ('active', models.NullBooleanField()),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'res_currency',
                'managed': False,
            },
        ),
    ]
