# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_resproduct_resproducttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('write_uid', models.IntegerField(blank=True, null=True)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('date_order', models.DateTimeField(blank=True, null=True)),
                ('partner_id', models.IntegerField(blank=True, null=True)),
                ('dest_address_id', models.IntegerField(blank=True, null=True)),
                ('fiscal_position', models.IntegerField(blank=True, null=True)),
                ('amount_untaxed', models.FloatField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('amount_tax', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(max_length=64)),
                ('pricelist_id', models.IntegerField(blank=True, null=True)),
                ('warehouse_id', models.IntegerField(blank=True, null=True)),
                ('payment_term_id', models.IntegerField(blank=True, null=True)),
                ('partner_ref', models.CharField(max_length=64)),
                ('date_approve', models.DateTimeField(blank=True, null=True)),
                ('amount_total', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice_method', models.CharField(max_length=64)),
                ('shipped', models.NullBooleanField()),
                ('validator', models.IntegerField(blank=True, null=True)),
                ('minimum_planned_date', models.DateTimeField(blank=True, null=True)),
                ('stock_state', models.CharField(max_length=64)),
                ('payment_tools_id', models.IntegerField(blank=True, null=True)),
                ('carrier_id', models.IntegerField(blank=True, null=True)),
                ('payment_mode', models.IntegerField(blank=True, null=True)),
                ('purchaser_id', models.IntegerField(blank=True, null=True)),
                ('spot_buying', models.NullBooleanField()),
                ('origin', models.CharField(max_length=64)),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('exception_reason', models.TextField(blank=True, null=True)),
                ('logistics_company', models.CharField(max_length=64)),
                ('track_number', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'purchase_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('write_uid', models.IntegerField(blank=True, null=True)),
                ('product_uom', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('price_unit', models.FloatField(blank=True, null=True)),
                ('move_dest_id', models.IntegerField(blank=True, null=True)),
                ('product_qty', models.FloatField(blank=True, null=True)),
                ('partner_id', models.IntegerField(blank=True, null=True)),
                ('invoiced', models.NullBooleanField()),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('date_planned', models.DateTimeField(blank=True, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('account_analytic_id', models.IntegerField(blank=True, null=True)),
                ('stock_in_date', models.DateTimeField(blank=True, null=True)),
                ('stock_state', models.CharField(blank=True, max_length=64, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('purchaser_id', models.IntegerField(blank=True, null=True)),
                ('purchase_state', models.CharField(blank=True, max_length=64, null=True)),
                ('should_purchase_qty_real', models.IntegerField(blank=True, null=True)),
                ('person_stock_id', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=64)),
                ('merge_before_qty', models.IntegerField(blank=True, null=True)),
                ('is_merge', models.CharField(max_length=64)),
                ('stockin_qty', models.IntegerField(blank=True, null=True)),
                ('invoice_repair_state', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_first', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'purchase_order_line',
                'managed': False,
            },
        ),
    ]
