# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_purchaseorder_purchaseorderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('write_uid', models.IntegerField(blank=True, null=True)),
                ('uom_type', models.CharField(blank=True, max_length=64, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('rounding', models.FloatField(blank=True, null=True)),
                ('factor', models.FloatField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
            ],
            options={
                'db_table': 'product_uom',
                'managed': False,
            },
        ),
    ]
