# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_productuom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('write_uid', models.IntegerField(blank=True, null=True)),
                ('currency_id', models.IntegerField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('active', models.NullBooleanField()),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_pricelist',
                'managed': False,
            },
        ),
    ]
