# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_productpricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('write_uid', models.IntegerField(blank=True, null=True)),
                ('lot_input_id', models.IntegerField(blank=True, null=True)),
                ('lot_output_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('lot_stock_id', models.IntegerField(blank=True, max_length=64, null=True)),
                ('partner_id', models.IntegerField(blank=True, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('nation', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.NullBooleanField()),
            ],
            options={
                'db_table': 'stock_warehouse',
                'managed': False,
            },
        ),
    ]
