# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_stockwarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarmerxInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('write_uid', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('stock_qty', models.IntegerField(blank=True, null=True)),
                ('last_out_date', models.DateTimeField(blank=True, null=True)),
                ('usable_qty', models.IntegerField(blank=True, null=True)),
                ('lock_qty', models.IntegerField(blank=True, null=True)),
                ('first_in_by', models.IntegerField(blank=True, null=True)),
                ('last_out_by', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('first_in_date', models.DateTimeField(blank=True, null=True)),
                ('last_in_date', models.DateTimeField(blank=True, null=True)),
                ('last_in_by', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('stock_up_qty', models.IntegerField(blank=True, null=True)),
                ('is_lock', models.NullBooleanField()),
            ],
            options={
                'db_table': 'starmerx_inventory',
                'managed': False,
            },
        ),
    ]
