# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_stcokmove_stcokpicking'),
    ]

    operations = [
        migrations.CreateModel(
            name='WkfInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkf_id', models.IntegerField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('res_id', models.IntegerField(blank=True, null=True)),
                ('res_type', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'wkf_instance',
                'managed': False,
            },
        ),
    ]
