# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_wkfinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WkfWorkitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.IntegerField(blank=True, null=True)),
                ('inst_id', models.IntegerField(blank=True, null=True)),
                ('subflow_id', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'wkf_workitem',
                'managed': False,
            },
        ),
    ]
