# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_wkfworkitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Invoice_Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField(blank=True, null=True)),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_invoice_rel',
                'managed': False,
            },
        ),
    ]
