# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_purchase_invoice_rel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarmerxInventoryWmsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('stock_qty', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'starmerx_inventory_wms_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockMoveWmsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_inventory_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_tmpl_id', models.IntegerField(blank=True, null=True)),
                ('default_code', models.CharField(blank=True, max_length=64, null=True)),
                ('name_template', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('price_unit', models.FloatField(blank=True, null=True)),
                ('product_qty', models.FloatField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=64, null=True)),
                ('picking_id', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('warehouse_id', models.IntegerField(blank=True, null=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=128, null=True)),
                ('stock_qty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_move_wms_report',
                'managed': False,
            },
        ),
    ]
